[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_sdist"

[project]
name = "bbutils"
version = "0.1"
description = "Bingbong's utility functions."
authors = [{name = "Bingbong"}]